applications:
  - name: "GCP Mumbai Production Environment"
    environments:
      - name: "Production"
        servers:
          - name: "Linux-Server"
            ip: 35.200.187.236
            os: "linux"
            services:
              - name: "Tomcat"
                type: "app"
                statusCmd: "systemctl status tomcat10"
                startupCmd: "systemctl start tomcat10"
                statusScript: "/opt/tomcat/bin/version.sh"
                startScript: "/opt/tomcat/bin/startup.sh"
              - name: "WildFly"
                type: "app"
                statusCmd: "systemctl status wildfly"
                startupCmd: "systemctl start wildfly"
                statusScript: "/opt/wildfly/bin/version.sh"
                startScript: "/opt/wildfly/bin/standalone.sh"
              - name: "SSH Service"
                type: "app"
                statusCmd: "systemctl status ssh"
                startupCmd: "systemctl start ssh"
                statusScript: "/opt/ssh/bin/version.sh"
                startScript: "/opt/ssh/bin/startup.sh"
          - name: "Windows-Server"
            ip: 35.200.246.189
            os: "windows"
            services:
              # - name: "Tomcat-Windows"
              #   type: "app"
              #   statusCmd: "Get-Service -Name Tomcat9"
              #   startupCmd: "Start-Service -Name Tomcat9"
              - name: "IIS"
                type: "app"
                statusCmd: "Get-Service -Name W3SVC"
                startupCmd: "Start-Service -Name W3SVC" 